# Generated by Django 4.2.27 on 2025-12-22 23:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('GROUND', 'Ground Station'), ('SAT', 'Satellite'), ('ROUTER', 'Router'), ('GENERIC', 'Generic')], default='GENERIC', max_length=20)),
                ('environment', models.CharField(choices=[('DEV', 'Development'), ('STAGE', 'Staging'), ('PROD', 'Production')], default='DEV', max_length=10)),
                ('mgmt_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('UNREACHABLE', 'Unreachable'), ('ERROR', 'Error')], default='PROVISIONING', max_length=20)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('desired_config_version', models.CharField(blank=True, max_length=50)),
                ('applied_config_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_type', models.CharField(choices=[('PROVISION', 'Provision Node'), ('APPLY_CONFIG', 'Apply Configuration'), ('RESTART_AGENT', 'Restart Agent')], max_length=50)),
                ('state', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('requested_by', models.CharField(default='system', max_length=100)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='network.node')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('RF', 'RF'), ('FIBER', 'Fiber'), ('VPN', 'VPN'), ('GENERIC', 'Generic')], default='GENERIC', max_length=20)),
                ('status', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('DEGRADED', 'Degraded')], default='UP', max_length=10)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('packet_loss', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='network.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='network.node')),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error'), ('STATE_CHANGE', 'State Change'), ('HEARTBEAT', 'Heartbeat')], default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='network.node')),
                ('workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='network.workflowrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
