# Generated by Django 4.2.27 on 2025-12-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='entity_id',
            field=models.CharField(blank=True, help_text='Partition key / Object ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='entity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='event_id',
            field=models.UUIDField(help_text='Idempotency key from Kafka', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Full event body'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error'), ('STATE_CHANGE', 'State Change'), ('HEARTBEAT', 'Heartbeat')], default='INFO', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='message',
            field=models.TextField(blank=True, help_text='Human readable summary'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['event_id'], name='network_eve_event_i_6f087e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['entity_id'], name='network_eve_entity__9743de_idx'),
        ),
    ]
